<a href="https://colab.research.google.com/github/LambdaTheda/CheatSheets/blob/master/S_mar21_11PM_REGRSS2_unit2_spr1_mod2_212_assmnt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 2*

---

# Regression 2

## Assignment

You'll continue to **predict how much it costs to rent an apartment in NYC,** using the dataset from renthop.com.

- [ ] Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
- [ ] Engineer at least two new features. (See below for explanation & ideas.)
- [ ] Fit a linear regression model with at least two features.
- [ ] Get the model's coefficients and intercept.
- [ ] Get regression metrics RMSE, MAE, and $R^2$, for both the train and test data.
- [ ] What's the best test MAE you can get? Share your score and features used with your cohort on Slack!
- [ ] As always, commit your notebook to your fork of the GitHub repo.


#### [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)

> "Some machine learning projects succeed and some fail. What makes the difference? Easily the most important factor is the features used." — Pedro Domingos, ["A Few Useful Things to Know about Machine Learning"](https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf)

> "Coming up with features is difficult, time-consuming, requires expert knowledge. 'Applied machine learning' is basically feature engineering." — Andrew Ng, [Machine Learning and AI via Brain simulations](https://forum.stanford.edu/events/2011/2011slides/plenary/2011plenaryNg.pdf) 

> Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work. 

#### Feature Ideas
- Does the apartment have a description?
- How long is the description?
- How many total perks does each apartment have?
- Are cats _or_ dogs allowed?
- Are cats _and_ dogs allowed?
- Total number of rooms (beds + baths)
- Ratio of beds to baths
- What's the neighborhood, based on address or latitude & longitude?

## Stretch Goals
- [ ] If you want more math, skim [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf),  Chapter 3.1, Simple Linear Regression, & Chapter 3.2, Multiple Linear Regression
- [ ] If you want more introduction, watch [Brandon Foltz, Statistics 101: Simple Linear Regression](https://www.youtube.com/watch?v=ZkjP5RJLQF4)
(20 minutes, over 1 million views)
- [ ] Add your own stretch goal(s) !

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import numpy as np
import pandas as pd

# Read New York City apartment rental listing data
pd.set_option('display.max_rows', None)

df = pd.read_csv(DATA_PATH+'apartments/renthop-nyc.csv')
assert df.shape == (49352, 34)

# Remove the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= np.percentile(df['price'], 0.5)) & 
        (df['price'] <= np.percentile(df['price'], 99.5)) & 
        (df['latitude'] >= np.percentile(df['latitude'], 0.05)) & 
        (df['latitude'] < np.percentile(df['latitude'], 99.95)) &
        (df['longitude'] >= np.percentile(df['longitude'], 0.05)) & 
        (df['longitude'] <= np.percentile(df['longitude'], 99.95))]

In [0]:
df.head(200)

     bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0          1.5         3  ...                 0                    0
1          1.0         2  ...                 0                    0
2          1.0         1  ...                 0                    0
3          1.0         1  ...                 0                    0
4          1.0         4  ...                 0                    0
5          2.0         4  ...                 0                    0
6          1.0         2  ...                 0                    0
7          2.0         1  ...                 0                    0
8          1.0         1  ...                 0                    0
9          2.0         4  ...                 0                    0
10         1.0         0  ...                 0                    0
11         1.0         1  ...                 0                    0
12         1.0         2  ...                 0                    0
13         2.0         2  ...                 0                    0
14         1.0         1  ...                 0                    0
15         1.0         0  ...                 0                    0
16         1.0         2  ...                 0                    0
17         1.0         1  ...                 0                    0
18         1.0         4  ...                 0                    0
19         1.0         1  ...                 0                    0
20         1.0         3  ...                 0                    0
21         1.0         2  ...                 0                    0
22         1.0         1  ...                 0                    0
23         1.0         1  ...                 0                    0
24         2.0         4  ...                 0                    0
25         3.5         4  ...                 0                    0
26         1.0         1  ...                 0                    0
27         1.0         1  ...                 0                    0
29         2.0         2  ...                 0                    0
30         1.0         0  ...                 0                    0
31         1.0         2  ...                 0                    0
32         1.0         1  ...                 0                    0
33         1.0         2  ...                 0                    0
34         1.0         2  ...                 0                    0
35         1.0         1  ...                 0                    0
37         1.0         0  ...                 0                    0
38         2.0         2  ...                 0                    0
39         1.0         0  ...                 0                    0
40         1.0         3  ...                 0                    0
41         3.0         4  ...                 1                    0
42         1.0         0  ...                 0                    0
43         1.0         0  ...                 0                    0
44         1.0         1  ...                 0                    0
45         1.0         1  ...                 0                    0
46         1.0         0  ...                 0                    0
47         1.0         2  ...                 0                    0
48         1.0         1  ...                 0                    0
49         1.0         2  ...                 0                    1
50         1.0         1  ...                 0                    0
51         1.0         1  ...                 0                    0
52         1.0         0  ...                 0                    0
53         1.0         1  ...                 0                    0
54         1.0         0  ...                 0                    0
55         2.0         2  ...                 0                    0
56         1.0         2  ...                 0                    0
57         1.0         0  ...                 0                    0
58         1.0         3  ...                 0                    1
59         1.0         1  ...                 0                    0
60         1.0         2  ...                 0                    0
61         1.0         1  ...                 0                    0
62         1.0         0  ...                 0                    0
63         1.0         2  ...                 0                    0
64         1.0         1  ...                 0                    0
65         1.0         1  ...                 0                    0
66         1.0         1  ...                 0                    0
67         1.0         1  ...                 0                    0
68         2.0         2  ...                 0                    0
69         1.0         2  ...                 0                    0
70         1.0         1  ...                 0                    0
71         1.0         2  ...                 0                    0
72         2.0         3  ...                 0                    0
73         1.0         1  ...                 0                    0
74         2.0         2  ...                 0                    0
75         2.0         2  ...                 0                    0
76         2.0         2  ...                 0                    0
77         1.0         2  ...                 1                    0
78         1.0         0  ...                 0                    0
79         1.0         1  ...                 0                    0
80         1.0         1  ...                 0                    0
81         1.0         1  ...                 1                    0
82         1.0         0  ...                 0                    0
83         1.0         3  ...                 0                    0
84         1.0         2  ...                 0                    0
85         3.5         4  ...                 0                    0
86         1.0         2  ...                 0                    0
87         1.0         0  ...                 0                    0
88         1.0         2  ...                 0                    0
89         1.0         1  ...                 1                    0
90         1.0         0  ...                 0                    0
91         1.0         1  ...                 0                    0
92         2.0         3  ...                 0                    0
93         1.0         3  ...                 0                    0
94         1.0         2  ...                 0                    0
95         1.0         2  ...                 0                    0
96         1.0         2  ...                 0                    0
97         1.0         3  ...                 0                    0
98         2.0         3  ...                 1                    0
99         1.0         1  ...                 0                    0
100        1.0         2  ...                 0                    0
101        2.0         2  ...                 0                    0
102        1.0         1  ...                 0                    0
103        1.0         1  ...                 0                    0
104        1.0         1  ...                 0                    0
105        1.0         2  ...                 0                    0
106        1.0         0  ...                 0                    0
107        1.0         1  ...                 0                    0
108        1.0         1  ...                 0                    0
109        1.0         1  ...                 0                    1
110        1.0         2  ...                 0                    0
111        1.5         2  ...                 0                    0
112        2.0         2  ...                 0                    0
113        2.0         2  ...                 0                    0
114        1.0         2  ...                 0                    0
115        1.0         1  ...                 0                    0
116        1.0         2  ...                 0                    0
117        1.0         1  ...                 0                    0
118        2.0         2  ...                 0                    0
119        1.0         1  ...                 0                    0
120        2.0         4  ...                 0                    0
121        1.0         1  ...                 0                    0
122        2.0         4  ...                 0                    0
123        1.0         0  ...                 0                    0
124        1.0         2  ...                 0                    0
125        1.0         1  ...                 0                    0
126        1.0         0  ...                 0                    0
127        2.0         3  ...                 0                    0
128        1.0         2  ...                 0                    0
129        1.0         0  ...                 0                    1
130        1.0         3  ...                 0                    0
131        1.0         2  ...                 0                    0
132        1.0         3  ...                 0                    0
133        1.0         0  ...                 0                    0
134        1.0         1  ...                 0                    0
135        1.0         3  ...                 0                    0
136        1.0         1  ...                 0                    0
137        1.0         2  ...                 0                    0
138        2.0         2  ...                 0                    0
139        1.0         0  ...                 0                    0
140        2.0         3  ...                 0                    0
141        2.0         1  ...                 0                    0
142        1.0         1  ...                 0                    0
143        1.0         0  ...                 0                    0
144        1.0         0  ...                 0                    0
145        1.0         1  ...                 0                    0
146        1.0         2  ...                 0                    0
147        1.0         1  ...                 1                    0
148        1.0         1  ...                 0                    0
149        1.0         3  ...                 0                    0
150        1.0         0  ...                 0                    0
151        1.0         1  ...                 0                    0
152        1.0         1  ...                 0                    0
153        1.0         1  ...                 0                    0
154        2.0         3  ...                 0                    0
155        1.0         2  ...                 0                    0
156        1.0         1  ...                 0                    0
157        2.0         3  ...                 1                    0
158        2.0         3  ...                 0                    0
160        2.0         2  ...                 0                    0
161        2.0         4  ...                 0                    0
162        1.0         0  ...                 0                    0
163        1.0         0  ...                 0                    0
164        1.0         1  ...                 0                    0
165        2.0         3  ...                 0                    0
166        2.0         2  ...                 0                    0
167        1.0         3  ...                 0                    0
168        1.0         2  ...                 0                    0
169        1.0         1  ...                 0                    0
170        1.0         1  ...                 0                    0
171        1.0         1  ...                 0                    0
172        2.0         2  ...                 0                    0
173        2.0         3  ...                 0                    0
174        1.0         1  ...                 0                    0
175        2.0         2  ...                 0                    0
176        1.0         2  ...                 0                    0
177        1.0         3  ...                 0                    0
178        1.0         1  ...                 0                    0
179        1.0         0  ...                 0                    0
180        1.0         0  ...                 1                    0
181        1.0         1  ...                 0                    0
182        1.0         1  ...                 0                    0
183        1.0         2  ...                 0                    0
184        1.0         1  ...                 0                    0
185        1.0         1  ...                 0                    0
186        1.0         1  ...                 0                    0
187        1.0         1  ...                 0                    0
188        1.0         2  ...                 0                    0
189        1.0         1  ...                 0                    0
190        1.0         2  ...                 0                    0
191        1.0         3  ...                 0                    0
192        1.0         3  ...                 0                    0
193        1.0         1  ...                 0                    1
194        1.0         1  ...                 0                    0
195        1.0         2  ...                 0                    0
196        1.0         1  ...                 0                    0
197        1.0         2  ...                 0                    0
198        2.0         3  ...                 0                    0
199        1.0         2  ...                 0                    0
200        1.0         1  ...                 0                    0
201        1.0         1  ...                 0                    0
202        2.0         3  ...                 0                    0

[200 rows x 34 columns]

In [0]:
df

In [0]:
df.shape

In [0]:
# Train/test split. Use data from April & May 2016 to train. 

df['created'] = pd.to_datetime(df['created'])
train = df[(df['created'].dt.year == 2016) & (df['created'].dt.month.isin([4, 5]))]
train.shape

In [0]:
# explore column to use for train/test split
df['created'].value_counts(48817) # returns counts as < 1 (bc of dt classes? or https://www.w3resource.com/pandas/series/series-value_counts.php- SERIES notdf fcngit)

In [0]:
df['created'].value_counts(48817).head(300)

In [0]:
# explore column to use for train/test split
df['created'].describe()

In [0]:
df['created'].shape

#  train/test split

In [0]:
#ATTEMPT 3: Parsing out only YEAR from df['created']-
df['created'] = pd.to_datetime(df['created']) #dot notation: df['created'] = pd.to_datetime(df.created); from https://www.youtube.com/watch?v=yCgJGsg0Xa4
df['year'] = df['created'].dt.year
df['year']

In [0]:
#temp df for making train set from df with df['created'].dt.year == 2016
df_train_yr = df[(df['year'] == 2016)]
df_train_yr.head(200)

In [0]:
df_train_yr.nunique

In [0]:
#df_train_yr.value_counts() #AttributeError: 'DataFrame' object has no attribute 'value_counts'; BC NO CLASSES ?#

In [0]:
#filter df_train_yr for April and May rows- WORKS
df_train_yr_and_months = df_train_yr[df_train_yr['created'].dt.month.isin([4, 5])]  #df[(df['year'] == 2016)]
df_train_yr_and_months.head(200)

In [0]:
df_train_yr_and_months.sample(300)

In [0]:
df_train = df_train_yr_and_months
df_train.head(300)

In [0]:
df_train.shape

# FILTER df_train TO MAKE TEST SET USING JUNE 2016 ROWS

In [0]:
df['created'] = pd.to_datetime(df['created'])
df['created'].dtype

In [0]:
# ATTEMPT 2: AttributeError: 'str' object has no attribute 'dt'
'''
df['created'] = pd.to_datetime(df['created'])

df['month'] = df['created'].dt.month

df_test = df_train_yr[df_train_yr['created'.dt.month] == 6] 
df_test
'''

In [0]:
# ATTEMPT 3: WORKS

df['created'] = pd.to_datetime(df['created'])
#df['created'].dtype            # RETURNS dtype('<M8[ns]')
df_test = df_train_yr[df_train_yr['created'].dt.month.isin([6])]
df_test.head(300)

In [0]:
df_test.shape

In [0]:
df_test['created'].value_counts()

# "my own" S t     r            e           T                c  h                                          GOAL!  3d plot of 3 features

In [0]:
import plotly.express as px
px.scatter_3d(
    df,
    x = 'bedrooms',
    y = 'price',
    z = 'bathrooms', 
    title = 'NYC Apartment Rental Prices, 2016'
)

# Engineer at least two new features.

In [0]:
# 1) Does the apartment have a description? ATTEMPTS/Exploration

# Using for loop
# for descrp in range (len(df['description'])):  

# Chris suggests apply():

 # use regex to find '     ' string that seems to represent no descriptions
'''
import re 
no = re.compile('        ')
no    # RETURNS: re.compile(r'        ', re.UNICODE)
'''

# 1) FEATURE ENGINEERED 'has_description' column:

In [0]:
# 1) FEATURE ENGINEERED 'has_description' column: Does the apartment have a description?
# set the new column to the dataframe column with all values EXCEPT '        '
df['has_description'] = ~df['description'].isin(['        '])

df['has_description'] = df['has_description'].map({True: 'Yes', False: 'No'})

df['has_description']

In [0]:
df.sample(200)

In [0]:
# use findall() 
'''
no.findall('        ')
print(df['description'].no.findall('        ')) # RETURNS: AttributeError: 'Series' object has no attribute 'no'
'''

# 2) FEATURE ENGINEERED 'total_rooms' column:

In [0]:
# 2) FEATURE ENGINEERED 'total_rooms' column: Total number of rooms (beds + baths)
df['total_rooms'] = df['bedrooms'] + df['bathrooms']
df.head()

In [0]:
#Check the columns
df.columns

# Fit a linear regression model with at least two features.

## 5 Step Process:

In [0]:
# 5 Step Process:
# 1) Import appropriate estimator class from sklearn

from sklearn.linear_model import LinearRegression

In [0]:
# 2) Instantiate this class
model = LinearRegression()

# 3 WAYS TO SPLIT TRAIN/TEST DATASETS/dataframes:

In [0]:
#3a) Arrange X FEATURES matrices- ONE WAY:

df['created'] = pd.to_datetime(df['created'], infer_datetime_format=True) # change dtype from string to datetime to access month, day, yr etc

# filter out year 2016
df['year_created'] = df['created'].dt.year    # access yr
df = df[df['year_created'] == 2016]

df['month_created'] = df['created'].dt.month  # access month

# filter out months Apr & May for TRAIN set
train = df[(df['month_created'] == 4) | (df['month_created'] == 5)]

# filter out month June for TEST set
test = df[df['month_created'] == 6]

In [0]:
train.shape, test.shape

In [0]:
#3b) Arrange X FEATURES MATRICES- a 2nd WAY

features = ['total_rooms', 'has_description'] # a python list, called features, containing these 2 columns' data

X_train = train[features] # split 2 chosen features' columns' row fields into train dataframe matrix
X_test  =  test[features] # split " " " " " " into test dataframe matrix

X_train, X_test #BEST WAY TO VISUALIZE? shape below? head()?

# Arrange y target Matrix
target = 'price'  # target is an sklearn df? attribute that allows one to access the target values (fields?) aka labels- CHRIS TL said NOT IN GENERAL
                  # else Colab/python (which) recognizes it as one of the columns (color change), and can ALWAYS? set a col to a var w/o calling?/using the df[]?
                   
y_train = train[target]  # predicted y target column (no x, only y) values output for passed in features datapoints in/from TRAIN DATASET/dataframe
y_test  =  test[target]  # predicted y target column (no x, only y) values output for passed in features datapoints in/from TEST DATASET/dataframe

In [0]:
print(f'Linear Regression, dependent upon: {features}')
print('X_train.shape: ', X_train.shape, '\n' ' X_test.shape: ', X_test.shape)

In [0]:
'''
# 3b) a 3rd way to split test/train using the TRAIN_TEST_SPLIT METHOD
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size = 0.2)
'''

In [0]:
#4) fit model on TRAIN DATASET
model.fit(X_train, y_train) # ValueError: could not convert string to float: 'Yes'- change to 1 = Yes, 0 = No, or One Hot Encode

In [0]:
#4a) One-hot encoding of 'has_description'
import category_encoders as ce

encoder = ce.OneHotEncoder(use_cat_names=True)

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

print(X_train_encoded.shape, X_test_encoded.shape)

(31844, 3) (16973, 3)

In [0]:
# 5a) calculate Train error
from sklearn.metrics import mean_absolute_error

y_pred = model.predict(X_train) # get prediction of y target values 
mae = mean_absolute_error(y_train, y_pred)
print(f'Train Error: {mae:.2f} percentage points')

In [0]:
# 5b) calculate Test error
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
print(f'Test Error: {mae:.2f} percentage points')

# Get the model's coefficients and intercept.

In [0]:
 model.coef_, model.intercept_

In [0]:
# equation for the model
beta0 = model.intercept_
beta1, beta2 = model.coef_
print(f'y = {beta0} + {beta1}x1 + {beta2}x2')

In [0]:
# model's coefficients and intercept. 
print('Intercept', model.intercept_)
coefficients = pd.Series(model.coef_, features)
print(coefficients.to_string())

## Get regression metrics RMSE, MAE, and  𝑅2 , for both the train and test data.

In [0]:
# Regression metrics for TRAIN data
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = model.predict(X_train)

mse = mean_squared_error(y_train, y_pred)  #Mean squared error

rmse = np.sqrt(mse)                        #root mean squared Error

mae = mean_absolute_error(y_train, y_pred) #mean absolute Error

r2 = r2_score(y_train, y_pred)             #r^2

print('Mean Squared Error:', mse)
print('Root Mean Squared Error:', rmse)
print('Mean Absolute Error:', mae)
print('R^2:', r2)

In [0]:
# Regression metrics for TEST data
y_pred = model.predict(X_test) 

mse = mean_squared_error(y_test, y_pred)  #Mean squared error

rmse = np.sqrt(mse)                       #root mean squared Error

mae = mean_absolute_error(y_test, y_pred) #mean absolute Error

r2 = r2_score(y_test, y_pred)             #r^2

print('Mean Squared Error:', mse)
print('Root Mean Squared Error:', rmse)
print('Mean Absolute Error:', mae)
print('R^2:', r2)